LabWork_2_2/Models/CalcTask.cs
namespace LabWork_2_2.Models
{
    public class Operation
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
    public class CalcTask
    {
        public int FirstNumber { get; set; }
        public int SecondNumber { get; set; }
        public int OperationId { get; set; }

    }
}

LabWork_2_2/Models/Solution.cs
namespace LabWork_2_2.Models
{
    public class Solution
    {
        public string Add { get; set; }
        public string Sub { get; set; }
        public string Mult { get; set; }
        public string Div { get; set; }
    }
}

LabWork_2_2/Models/View.cs
namespace LabWork_2_2.Models
{
    public class View
    {
        public CalcTask Task { get; set; }
        public Solution Solution { get; set; }

        public View()
        {
            Task = new CalcTask();
            Solution = new Solution();
        }
    }
}

LabWork_2_2/Controllers/CalcServiceController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using LabWork_2_2.Services;
using LabWork_2_2.Models;


namespace LabWork_2_2.Controllers
{
    public class CalcServiceController : Controller
    {

        private readonly ICalculator _calculator;
        private readonly ITaskGenerator _generator;
        public CalcServiceController(ICalculator calculator, ITaskGenerator generator)
        {
            this._calculator = calculator;
            this._generator = generator;
        }

        IEnumerable<Operation> operations = new List<Operation>
        {
            new Operation { Id = 1, Name = "+" },
            new Operation { Id = 2, Name = "-" },
            new Operation { Id = 3, Name = "*" },
            new Operation { Id = 4, Name = "/"}
        };

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ModelBinding()
        {
            ViewBag.Operations = new SelectList(operations, "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult ModelBinding(CalcTask task)
        {
            ViewBag.Operations = new SelectList(operations, "Id", "Name");
            ViewBag.Result = _calculator.Solution(task);
            return View();
        }

        public IActionResult Manual()
        {
            ViewBag.Operations = new SelectList(operations, "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Manual(int FirstNumber, int SecondNumber, int OperationId)
        {
            CalcTask task = new CalcTask { FirstNumber = FirstNumber, SecondNumber = SecondNumber, OperationId = OperationId };
            ViewBag.Operations = new SelectList(operations, "Id", "Name");
            ViewBag.Result = _calculator.Solution(task);
            return View();
        }

        public IActionResult Inject()
        {
            ViewBag.Operations = new SelectList(operations, "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Inject(CalcTask task)
        {
            ViewBag.Operations = new SelectList(operations, "Id", "Name");
            ViewBag.Task = task;
            return View();
        }
    }
}

LabWork_2_2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace LabWork_2_2.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LabWork_2_2/Views/CalcService/Inject.cshtml
@{
    ViewData["Title"] = "Inject Service";
}

@inject LabWork_2_2.Services.ICalculator calc
@model LabWork_2_2.Models.CalcTask
@* Построение формы с использованием tag helper *@

<div>
    <h3>Inject Service</h3>
</div>

<form asp-action="Inject" asp-controller="CalcService" asp-antiforgery="true">
    <div>
        <label><b>First Number</b></label>
        <input type="number" asp-for="FirstNumber" />
    </div>
    <div>
        <label><b>Operation</b></label>
        <select asp-for="OperationId" asp-items="ViewBag.Operations"></select>
    </div>
    <div>
        <label><b>Second Number</b></label>
        <input type="number" asp-for="SecondNumber" />
    </div>
    <div>
        <input type="submit" value="Submit" />
    </div>
</form>

@if (ViewBag.Task != null)
{
    <div>
        <h3>Result</h3>
    </div>
    <div>
        <label><b>@calc.Solution(ViewBag.Task)</b></label>
    </div>
}

LabWork_2_2/Views/CalcService/Manual.cshtml
@{
    ViewData["Title"] = "Pass Using Model";
}

@* Построение формы с использованием html helper *@

<div>
    <h3>Model Binding In Parameters</h3>
</div>

@using (Html.BeginForm("Manual", "CalcService", FormMethod.Post))
{
    <div>
        <label><b>First Number</b></label>
        @Html.TextBox("FirstNumber", "", new { type = "number" })
    </div>
    <div>
        <label><b>Operation</b></label>
        @Html.DropDownList("OperationId", ViewBag.Operations,"", "")
    </div>
    <div>
        <label><b>Second Number</b></label>
        @Html.TextBox("SecondNumber", "", new { type = "number" })
    </div>
    <div>
        <input type="submit" value="Submit" />
    </div>
}


@if (ViewBag.Result != null)
{
    <div>
        <h3>Result</h3>
    </div>
    <div>
        <label><b>@ViewBag.Result</b></label>
    </div>
}

LabWork_2_2/Views/CalcService/ModelBinding.cshtml
@{
    ViewData["Title"] = "Pass Using Model";
}

@model LabWork_2_2.Models.CalcTask
@* Построение формы с использованием tag helper *@

<div>
    <h3>Model Binding In Parameters</h3>
</div>

<form asp-action="ModelBinding" asp-controller="CalcService" asp-antiforgery="true">
    <div>
        <label><b>First Number</b></label>
        <input type="number" asp-for="FirstNumber" />
    </div>
    <div>
        <label><b>Operation</b></label>
        <select asp-for="OperationId" asp-items="ViewBag.Operations"></select>
    </div>
    <div>
        <label><b>Second Number</b></label>
        <input type="number" asp-for="SecondNumber" />
    </div>
    <div>
        <input type="submit" value="Submit" />
    </div>
</form>

@if (ViewBag.Result != null)
{
    <div>
        <h3>Result</h3>
    </div>
    <div>
        <label><b>@ViewBag.Result</b></label>
    </div>
}

LabWork_2_2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h3>Form parameters parsing</h3>
</div>

<p>
    <big>
        <ul>
            <li><a asp-area="" asp-controller="CalcService" asp-action="Manual">Manual (parameters)</a></li>
            <li><a asp-area="" asp-controller="CalcService" asp-action="Inject">Inject Service</a></li>
            <li><a asp-area="" asp-controller="CalcService" asp-action="ModelBinding">Model binding (parameters)</a></li>
        </ul>
    </big>
</p>

LabWork_2_2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LabWork_2_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LabWork_2_2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - LabWork_2_2 </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>